### ISSUE TITLE
Rolespecific Convars not showing in ULX

### ISSUE THREAD

**Issue by turulix** [TTT-2/ttt2-role_shini#14]
Hey,
ttt2_shinigami_speed and ttt2_shinigami_health_loss are not shown in the ULX settings for the role. Is it possible to add these?
Because the Jester role does have the specific settings in ULX

**Comment by saibotk** [comment]
Oh, seems like I did not add them yet, sorry for the inconvenience!

I will add them next week, when I'm done with exams :)

Thank you for reporting the bug!
