### ISSUE TITLE
Shinigami does not have a RemoveRoleLoadout

### ISSUE THREAD

**Issue by The1337Gh0st** [TTT-2/ttt2-role_shini#24]
I noticed that Shinigami does not have a RemoveRoleLoadout function, meaning that it could keep its items upon having its role changed. This could be fixed with the following code:

`function ROLE:RemoveRoleLoadout(ply, isRoleChange)
ply:StripWeapon("weapon_ttt_shinigamiknife")
		ply:Give("weapon_zm_improvised")
ply:Give("weapon_zm_carry")
ply:Give("weapon_ttt_unarmed")
	end
`

**Comment by saibotk** [comment]
Oh you're right
Thank you for noticing, will fix as soon as i got some time left.

Ping me if i have not done this in a reasonable time lol :D

**Comment by The1337Gh0st** [comment]
@saibotk Hey it's been almost 4 months, could you fix it?
