### ISSUE TITLE
A small inconvenience and offer to remove them.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_shini#3]
So as a Shinigami innocent, then following this, when he is reborn, he can see who killer is, but allowing him to speak, it is easier to give all the traitors and all at once, then the game is lost and I believe that it is necessary to remove the opportunity for him to speak, or write, that he knew who the killer was and could kill, but could not tell his companions.

**Comment by TimGoll** [comment]
Actually. right now it is already intended to be played this way. One could enforce this in lua though.

**Comment by Histalek** [comment]
Should be fixed by af05e30 .
