### ISSUE TITLE
Shinigami Zombies nehmen schaden

### ISSUE THREAD

**Issue by Gensokian** [TTT-2/ttt2-role_shini#4]
Wenn ein Shinigami getötet wurde, und dessen Leiche von einem Necromancer wiederbelebt wird, so tickt sein Leben wieder herunter, auch wenn dieser ein Zombie ist. (Also technisch gesehen kein shini mehr)

**Comment by TimGoll** [comment]
da wird wohl ein timer nicht gelöscht :D

**Comment by saibotk** [comment]
> da wird wohl ein timer nicht gelöscht :D

Das ist kein Timer, dass ist absichtlich so.

**Comment by TimGoll** [comment]
aber wenn man zB sich forcerespawned, dann stirbt man noch immer, auch wenn man die Rolle wechselt.
