### ISSUE TITLE
Change shinigami confirmation!

### ISSUE THREAD

**Issue by Lunethia** [TTT-2/ttt2-role_shini#6]
Okay, so this is a little feature request, that I've seen pop up here and there for a while now.

It's about how the shinigami is confirmed. In general the shinigami doesn't know that he's actually shinigami until he respawns. And so nobody else really knows either.
UNTIL the shinigami gets confirmed before respawning. Then it'll be clear for everyone that this player wasn't an innocent. 
![image](https://user-images.githubusercontent.com/52287610/76473082-bbf9be80-63f7-11ea-9841-dc8a3113c3c3.png)

The part that many people think could be improved, is confirming the shinigami as an innocent.
Since, as he is right now, a traitor that killed the shinigami when they were innocent, can simply camp the corpse to get an easy kill on the shinigami after respawning.

I'd suggest adding a convar (and code, lol) to make the shinigami be confirmed as an innocent, at least before he turns to be a shinigami, if he died a secoond time as shinigami he should probably also be confirmed as such.

**Comment by Histalek** [comment]
this was implemented by 4650eaaf3649a6f3416a4342d88e168a4df3ea97
